### ISSUE TITLE
[FR-10] Financial Literacy Resources

### ISSUE THREAD

**Issue by hi1314-griffindickson** [WSU-4110/SmartMoney#10]
### Goal

Provide financial literacy resources to users.

### Description

The system will provide articles, videos, tips, and tools in order to help the users with their finance. There will be resources for helping users with budgeting, saving, and investments. 

### Stakeholders

Users

### Date

9/18/2024

### Version

0.1

### Origin

Meeting #1

### Priority of the proposed feature

Should have

**Comment by gi5229** [comment]
*Changed proposal feature from "should have" to "nice to have" 
Ended up not implementing this feature in favor of focusing more on "must have" features
