### ISSUE TITLE
[FR-11] Cloud Backups

### ISSUE THREAD

**Issue by hi1314-griffindickson** [WSU-4110/SmartMoney#11]
### Goal

Provide secure cloud backups for our server and user data

### Description

The system will automatically periodically back up all user data as well as our server. In the event of a system failure, only data recorded past the last back up will be lost resulting in safer data storage. 

### Stakeholders

Users and Developers

### Date

09/18/2024

### Version

0.1

### Origin

Meeting #1

### Priority of the proposed feature

Must have

**Comment by Coiny555** [comment]
Used an api called Plaid to cover this.
