### ISSUE TITLE
[NFR-3] Reliability

### ISSUE THREAD

**Issue by hi1314-griffindickson** [WSU-4110/SmartMoney#13]
### Goal

The system is reliable and consistent

### Description

System rate at which the system fails should be less than 0.1% of time over the course of a year. There should be specific messages that will appear to help users with the error that they are encountering. Critical services such as financial history should have a failover mechanism for continuous functionality despite system failure.

### Stakeholders

All

### Date

9/18/2024

### Version

0.1

### Origin

Meeting #1

### Priority of the proposed feature

Must have

**Comment by Coiny555** [comment]
Implemented a feature that made a continuous integration of financial history regardless of errors on the app.
