### ISSUE TITLE
[NFR-6] Scalability

### ISSUE THREAD

**Issue by hi1314-griffindickson** [WSU-4110/SmartMoney#17]
### Goal

Users will be able to use the app simultaneously 

### Description

The app should be able to handle at least 10,000 users simultaneously using the app.

### Stakeholders

All

### Date

9/18/2024

### Version

0.1

### Origin

Meeting #1

### Priority of the proposed feature

Must have

**Comment by Coiny555** [comment]
App will be able to handle it as we have tested making multiple accounts on the app.
