### ISSUE TITLE
[BUG] Dark Mode Persistency issues

### ISSUE THREAD

**Issue by gi5229** [WSU-4110/SmartMoney#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Dark mode is not fully working on certain parts of pages.
Dark mode is turned off after users exit and reenter the app.

### Expected Behavior

Dark mode should remain consistent throughout the tabs within the app. 
Dark mode should remain consistent throughout entering and exiting the app.

### Steps To Reproduce

Go to settings.
Turn on Dark mode.
Click other tabs and inspect them. 
Open / Close the app multiple times and inspect.

### Environment

```markdown
- OS:IOS/macOS
- Expo:51.0.32
- Node:6.0.0
- React:18.2.0
```

**Comment by hi1314-griffindickson** [comment]
I have resolved the dark mode persistence issue. The main cause of this being the lack of async storage resulting in the app. When users close the app it will now remember their app appearance settings instead of forgetting.
