### ISSUE TITLE
[BUG] Dark Mode Colors Not Applied to Graphs

### ISSUE THREAD

**Issue by paarth-desai** [WSU-4110/SmartMoney#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When switching to dark mode, the graphs in the app do not update their colors to match the dark mode theme.

### Expected Behavior

The graphs should adopt the dark mode color scheme. For example, dark backgrounds and contrasting text.

### Steps To Reproduce

1. Open the settings screen.
2. Enable dark mode.
3. Navigate to the budget planner or financial overview screen.

### Environment

```markdown
- OS:IOS/macOS
- Expo:51.0.32
- Node:6.0.0
- React:18.2.0
```

**Comment by hi1314-griffindickson** [comment]
In order for darkmode to work new pages must be wrapped in toggleTheme.

**Comment by hi1314-griffindickson** [comment]
;)
