### ISSUE TITLE
[BUG] <Protected Status Bar>

### ISSUE THREAD

**Issue by hi1314-griffindickson** [WSU-4110/SmartMoney#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The status bar is not protected so when scrolling down status icons get in the way of text.

### Expected Behavior

Status bar should have a protected area that prevents status icons from displaying directly on the app.

### Steps To Reproduce

Open app and scroll down. 

### Environment

```markdown
- OS:IOS/macOS
- Expo:51.0.32
- Node:6.0.0
- React:18.2.0
```

**Comment by paarth-desai** [comment]
This issue has been resolved in the latest commit. The status bar now has a protected area to prevent icons from overlapping with app content.
