### ISSUE TITLE
[FR-4] Report a Bug

### ISSUE THREAD

**Issue by hi1314-griffindickson** [WSU-4110/SmartMoney#4]
### Goal

Users will be able to report bugs to the developers. 

### Description

Users can submit a brief description of the bug they are encountering using a form from the application. This form then will be submitted to the developers in order for them to enhance the website.

### Stakeholders

Users, Developers

### Date

9/18/2024

### Version

0.1

### Origin

Meeting #1

### Priority of the proposed feature

Could have

**Comment by gi5229** [comment]
report a bug feature fully functional (implemented by Paarth)
