### ISSUE TITLE
[FR-5] Financial History

### ISSUE THREAD

**Issue by hi1314-griffindickson** [WSU-4110/SmartMoney#5]
### Goal

Show users their financial history and fetch specific data. 

### Description

Customers will see their financial history and all of their previously logged transactions in the SmartMoney application. Customers will also be able to view specific transactions. 

### Stakeholders

Users

### Date

9/17/2024

### Version

0.1

### Origin

Meeting #1

### Priority of the proposed feature

Must have

**Comment by Coiny555** [comment]
Covered with Plaid.
