### ISSUE TITLE
[FR-6] View Income and Expenses

### ISSUE THREAD

**Issue by hi1314-griffindickson** [WSU-4110/SmartMoney#6]
### Goal

Users will be able to see their income and expenses. 

### Description

The system will allow its users to view their gross income and expenses. Expenses will be listed as well as categorized by type.

### Stakeholders

Users

### Date

9/17/2024

### Version

0.1

### Origin

Meeting #1

### Priority of the proposed feature

Must have

**Comment by Coiny555** [comment]
Plaid cover this. When you put your card information in the app, then on the financial history page, you will be able to see what you bought or earned.
