### ISSUE TITLE
[FR-7] Forgot Username or Password

### ISSUE THREAD

**Issue by hi1314-griffindickson** [WSU-4110/SmartMoney#7]
### Goal

Users will be able to reset their username or password. 

### Description

If users forget their information or if their information is breached they are able to change their username and or password within the SmartMoney application. Users will request this action by clicking on a button that displays "Forgot username / password".

### Stakeholders

Users

### Date

9/19/2024

### Version

0.1

### Origin

Meeting #1

### Priority of the proposed feature

Must have

**Comment by gi5229** [comment]
This feature is handled by our Auth0 API, all login/user information is created/stored/recovered through the auth0 splash page on the app and can be configured on the Auth0 website/dashboard.
