### ISSUE TITLE
[FR-8] User Authentication 

### ISSUE THREAD

**Issue by hi1314-griffindickson** [WSU-4110/SmartMoney#8]
### Goal

Secure user accounts using two step authentication process.

### Description

If the user would like, they can configure the SmartMoney application to have two step authentication. If applied the SmartMoney application will ask the user a question only they could know. This will act as a second password and will be entered along with the password in order to enter the application. 

### Stakeholders

Users

### Date

9/18/2024

### Version

0.1

### Origin

Meeting #1

### Priority of the proposed feature

Must have

**Comment by gi5229** [comment]
issue is now closed, implemented this with auth0 api.
