### ISSUE TITLE
[FR-9] Achievements

### ISSUE THREAD

**Issue by hi1314-griffindickson** [WSU-4110/SmartMoney#9]
### Goal

Gamifying SmartMoney and giving users rewards for good finances.

### Description

Users will earn badges based on different financial achievements that they have accomplished. For instance different percentages of saved income.

### Stakeholders

Users

### Date

9/18/2024

### Version

0.1

### Origin

Meeting #1

### Priority of the proposed feature

Could have

**Comment by gi5229** [comment]
Prioritized PLAID API over achievements
